"""add flagged column

Revision ID: 3b27d45fd093
Revises: 992b4091aa6d
Create Date: 2026-04-12 13:46:51.139367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b27d45fd093'
down_revision = '992b4091aa6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_records', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
