"""add photo_filename to cow

Revision ID: 3d16b30bb860
Revises: 3b27d45fd093
Create Date: 2026-04-18 05:43:23.773141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d16b30bb860'
down_revision = '3b27d45fd093'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_filename', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cows', schema=None) as batch_op:
        batch_op.drop_column('photo_filename')

    # ### end Alembic commands ###
